import { Student, Complaint, Announcement } from "../types";

export const STUDENTS: Student[] = [
  { id: "s001", name: "Arjun Sharma", room: "A101", block: "A", email: "arjun@iter.ac.in", phone: "9876543210", course: "B.Tech CSE", year: 2, password: "hostel" },
  { id: "s002", name: "Priya Patel", room: "A102", block: "A", email: "priya@iter.ac.in", phone: "9876543211", course: "B.Tech ECE", year: 1, password: "hostel" },
  { id: "s003", name: "Rahul Nayak", room: "B201", block: "B", email: "rahul@iter.ac.in", phone: "9876543212", course: "B.Tech ME", year: 3, password: "hostel" },
  { id: "s004", name: "Sneha Das", room: "B202", block: "B", email: "sneha@iter.ac.in", phone: "9876543213", course: "B.Tech Civil", year: 2, password: "hostel" },
  { id: "s005", name: "Vikram Singh", room: "C301", block: "C", email: "vikram@iter.ac.in", phone: "9876543214", course: "B.Tech CSE", year: 4, password: "hostel" },
  { id: "s006", name: "Ananya Mishra", room: "C302", block: "C", email: "ananya@iter.ac.in", phone: "9876543215", course: "B.Tech IT", year: 1, password: "hostel" },
  { id: "s007", name: "Rohan Behera", room: "D401", block: "D", email: "rohan@iter.ac.in", phone: "9876543216", course: "B.Tech EEE", year: 3, password: "hostel" },
  { id: "s008", name: "Pooja Rath", room: "D402", block: "D", email: "pooja@iter.ac.in", phone: "9876543217", course: "B.Tech CSE", year: 2, password: "hostel" },
  { id: "s009", name: "Aditya Kumar", room: "A103", block: "A", email: "aditya@iter.ac.in", phone: "9876543218", course: "B.Tech ME", year: 1, password: "hostel" },
  { id: "s010", name: "Kavya Reddy", room: "B203", block: "B", email: "kavya@iter.ac.in", phone: "9876543219", course: "B.Tech CSE", year: 4, password: "hostel" },
  { id: "s011", name: "Saurav Mohanty", room: "C303", block: "C", email: "saurav@iter.ac.in", phone: "9876543220", course: "B.Tech ECE", year: 2, password: "hostel" },
  { id: "s012", name: "Debasmita Sahoo", room: "D403", block: "D", email: "debasmita@iter.ac.in", phone: "9876543221", course: "B.Tech IT", year: 3, password: "hostel" },
];

export const WARDEN = { id: "w001", name: "Dr. Ramesh Patnaik", password: "hostel" };

function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 3600000);
}
function hoursFromNow(h: number): Date {
  return new Date(Date.now() + h * 3600000);
}

const SLA_HOURS: Record<string, number> = { urgent: 4, high: 24, medium: 72, low: 168 };

function makeSLA(priority: string, createdAt: Date) {
  const deadlineHours = SLA_HOURS[priority];
  const deadlineAt = new Date(createdAt.getTime() + deadlineHours * 3600000);
  const hoursLeft = (deadlineAt.getTime() - Date.now()) / 3600000;
  return { deadlineHours, deadlineAt, breached: hoursLeft < 0, hoursLeft: Math.max(hoursLeft, 0) };
}

export const SEED_COMPLAINTS: Complaint[] = [
  {
    id: "c001", receiptId: "CW-2026-001", studentId: "s001", studentName: "Arjun Sharma",
    room: "A101", block: "A", category: "maintenance", title: "Water leaking from ceiling pipe",
    description: "There is a severe water leak from the pipe near the ceiling of my room. Water is flooding the floor and damaging my belongings. This is a dangerous situation.",
    status: "in_progress", priority: "urgent",
    aiTags: ["leak", "flood", "dangerous"], aiNote: "Urgent: flooding/leak keywords detected",
    createdAt: hoursAgo(2), updatedAt: hoursAgo(1),
    sla: makeSLA("urgent", hoursAgo(2)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "Plumber dispatched immediately", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: ["s009"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c002", receiptId: "CW-2026-002", studentId: "s003", studentName: "Rahul Nayak",
    room: "B201", block: "B", category: "wifi", title: "Internet completely disconnected since 3 days",
    description: "The WiFi router on the second floor of Block B has been completely disconnected for the past 3 days. Cannot attend online classes. Signal is zero throughout the floor.",
    status: "acknowledged", priority: "high",
    aiTags: ["internet", "disconnected", "router"], aiNote: "High: connectivity issue",
    createdAt: hoursAgo(20), updatedAt: hoursAgo(18),
    sla: makeSLA("high", hoursAgo(20)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "ISP team notified", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: ["s004", "s010"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c003", receiptId: "CW-2026-003", studentId: "s005", studentName: "Vikram Singh",
    room: "C301", block: "C", category: "mess", title: "Stale food served in mess repeatedly",
    description: "The mess has been serving stale dal and bad food for the past week. Several students have reported stomach issues. The hygiene standards are very poor.",
    status: "open", priority: "high",
    aiTags: ["stale food", "bad food", "hygiene"], aiNote: "High: food quality issue",
    createdAt: hoursAgo(5), updatedAt: hoursAgo(5),
    sla: makeSLA("high", hoursAgo(5)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: ["s001", "s002", "s006", "s011"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c004", receiptId: "CW-2026-004", studentId: "s007", studentName: "Rohan Behera",
    room: "D401", block: "D", category: "maintenance", title: "Ceiling fan not working",
    description: "The ceiling fan in my room has stopped working. It was making a loud noise for a week and now it has completely stopped. The room is very hot without a fan.",
    status: "resolved", priority: "medium",
    aiTags: ["fan", "not working"], aiNote: "Medium: appliance issue",
    createdAt: hoursAgo(96), updatedAt: hoursAgo(24),
    sla: makeSLA("medium", hoursAgo(96)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "Maintenance team assigned", resolutionNote: "Fan replaced with new unit. All working now.",
    resolvedAt: hoursAgo(24),
    studentConfirmed: true, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: 4, satisfactionComment: "Good response but took a bit long",
    slaBreachEmailSent: false, upvotes: ["s012"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c005", receiptId: "CW-2026-005", studentId: "s002", studentName: "Priya Patel",
    room: "A102", block: "A", category: "personal", title: "Ragging complaint — anonymous",
    description: "I have been facing ragging from senior students in Block A corridor every night. It is affecting my mental health and studies. I am scared to report openly.",
    status: "open", priority: "urgent",
    aiTags: ["ragging", "harassment"], aiNote: "Urgent: ragging/harassment detected",
    createdAt: hoursAgo(1), updatedAt: hoursAgo(1),
    sla: makeSLA("urgent", hoursAgo(1)),
    isPrivate: true, isAnonymous: true,
    wardenNote: "", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: [], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c006", receiptId: "CW-2026-006", studentId: "s008", studentName: "Pooja Rath",
    room: "D402", block: "D", category: "maintenance", title: "No hot water in bathrooms",
    description: "The water heater in Block D bathrooms has not been working for 5 days. We have to take cold showers in the morning which is very uncomfortable especially in winter.",
    status: "in_progress", priority: "high",
    aiTags: ["no hot water"], aiNote: "High: amenity failure",
    createdAt: hoursAgo(30), updatedAt: hoursAgo(6),
    sla: makeSLA("high", hoursAgo(30)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "Geyser repair in progress", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: true,
    upvotes: ["s007", "s012"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c007", receiptId: "CW-2026-007", studentId: "s004", studentName: "Sneha Das",
    room: "B202", block: "B", category: "room", title: "Mattress is broken and damaged",
    description: "The mattress on my bed is completely broken with exposed springs. It is very uncomfortable to sleep and affecting my health. Requesting a replacement.",
    status: "pending_confirmation", priority: "medium",
    aiTags: ["mattress", "broken", "damaged"], aiNote: "Medium: room furnishing issue",
    createdAt: hoursAgo(80), updatedAt: hoursAgo(10),
    sla: makeSLA("medium", hoursAgo(80)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "Replacement arranged", resolutionNote: "New mattress installed in room B202. Please confirm.",
    resolvedAt: hoursAgo(10),
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: [], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c008", receiptId: "CW-2026-008", studentId: "s006", studentName: "Ananya Mishra",
    room: "C302", block: "C", category: "maintenance", title: "Cockroach infestation in room",
    description: "There are cockroaches coming out of the drainage in my room every night. Found at least 15 cockroaches yesterday. The drain has a foul smell too.",
    status: "open", priority: "urgent",
    aiTags: ["cockroach", "foul smell"], aiNote: "Urgent: pest infestation",
    createdAt: hoursAgo(3), updatedAt: hoursAgo(3),
    sla: makeSLA("urgent", hoursAgo(3)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: ["s005", "s011"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c009", receiptId: "CW-2026-009", studentId: "s010", studentName: "Kavya Reddy",
    room: "B203", block: "B", category: "maintenance", title: "Electrical wiring exposed in corridor",
    description: "There are exposed electrical wires hanging from the ceiling in the Block B second floor corridor near room 203. This is extremely dangerous and someone could get an electric shock.",
    status: "open", priority: "urgent",
    aiTags: ["electric shock", "dangerous", "wiring"], aiNote: "Urgent: electrical hazard",
    createdAt: hoursAgo(0.5), updatedAt: hoursAgo(0.5),
    sla: makeSLA("urgent", hoursAgo(0.5)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: ["s003", "s004"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c010", receiptId: "CW-2026-010", studentId: "s011", studentName: "Saurav Mohanty",
    room: "C303", block: "C", category: "wifi", title: "Low internet bandwidth during exams",
    description: "The internet speed in Block C drops to nearly zero during evening hours from 7pm to 10pm. This is the crucial study time and we cannot access any online resources.",
    status: "resolved", priority: "medium",
    aiTags: ["bandwidth", "internet"], aiNote: "Medium: connectivity issue",
    createdAt: hoursAgo(200), updatedAt: hoursAgo(72),
    sla: makeSLA("medium", hoursAgo(200)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "Bandwidth upgrade requested", resolutionNote: "Additional bandwidth allocated to Block C. Issue should be resolved.",
    resolvedAt: hoursAgo(72),
    studentConfirmed: true, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: 5, satisfactionComment: "Excellent! Works perfectly now.",
    slaBreachEmailSent: false, upvotes: ["s005", "s006"], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c011", receiptId: "CW-2026-011", studentId: "s009", studentName: "Aditya Kumar",
    room: "A103", block: "A", category: "mess", title: "Food poisoning from mess food",
    description: "I had food poisoning after eating dinner at the mess last night. I have been vomiting since midnight and have fever. The fish curry smelled bad when served.",
    status: "open", priority: "urgent",
    aiTags: ["food poisoning", "vomiting", "fever"], aiNote: "Urgent: health emergency",
    createdAt: hoursAgo(4.5), updatedAt: hoursAgo(4.5),
    sla: makeSLA("urgent", hoursAgo(4.5)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "", resolutionNote: "", resolvedAt: undefined,
    studentConfirmed: undefined, studentRejectedAt: undefined, resolutionRejectedCount: 0,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: false,
    upvotes: [], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
  {
    id: "c012", receiptId: "CW-2026-012", studentId: "s012", studentName: "Debasmita Sahoo",
    room: "D403", block: "D", category: "maintenance", title: "Bathroom tap broken — no water supply",
    description: "The main tap in my bathroom is broken and no water is coming. I cannot use the bathroom at all. The tap handle has completely broken off.",
    status: "reopened", priority: "high",
    aiTags: ["tap", "no water", "broken"], aiNote: "High: water supply issue",
    createdAt: hoursAgo(50), updatedAt: hoursAgo(2),
    sla: makeSLA("high", hoursAgo(50)),
    isPrivate: false, isAnonymous: false,
    wardenNote: "Plumber visited", resolutionNote: "Tap replaced.", resolvedAt: hoursAgo(12),
    studentConfirmed: false, studentRejectedAt: hoursAgo(2), resolutionRejectedCount: 1,
    satisfactionRating: undefined, satisfactionComment: undefined, slaBreachEmailSent: true,
    upvotes: [], groupId: undefined, duplicateOf: undefined, voiceTranscript: undefined,
  },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann001", title: "Water Supply Interruption — Block A & B",
    description: "Water supply in Block A and B will be interrupted from 10 AM to 2 PM on Monday for pipe maintenance work. Please store water in advance.",
    affectedBlocks: ["A", "B"],
    startTime: hoursFromNow(12), endTime: hoursFromNow(16),
    category: "maintenance", createdBy: "w001", createdAt: hoursAgo(2), isActive: true,
  },
  {
    id: "ann002", title: "Mess Menu Change — Special Dinner",
    description: "Special dinner will be served on Saturday evening to celebrate Annual Day. All students are invited. Menu includes special Odia thali.",
    affectedBlocks: ["All"],
    startTime: hoursFromNow(24), endTime: hoursFromNow(28),
    category: "event", createdBy: "w001", createdAt: hoursAgo(5), isActive: true,
  },
];
